routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Class Room
    Route::delete('class-rooms/destroy', 'ClassRoomController@massDestroy')->name('class-rooms.massDestroy');
    Route::post('class-rooms/parse-csv-import', 'ClassRoomController@parseCsvImport')->name('class-rooms.parseCsvImport');
    Route::post('class-rooms/process-csv-import', 'ClassRoomController@processCsvImport')->name('class-rooms.processCsvImport');
    Route::resource('class-rooms', 'ClassRoomController');

    // Lesson Category
    Route::delete('lesson-categories/destroy', 'LessonCategoryController@massDestroy')->name('lesson-categories.massDestroy');
    Route::post('lesson-categories/parse-csv-import', 'LessonCategoryController@parseCsvImport')->name('lesson-categories.parseCsvImport');
    Route::post('lesson-categories/process-csv-import', 'LessonCategoryController@processCsvImport')->name('lesson-categories.processCsvImport');
    Route::resource('lesson-categories', 'LessonCategoryController');

    // Tuition Package
    Route::delete('tuition-packages/destroy', 'TuitionPackageController@massDestroy')->name('tuition-packages.massDestroy');
    Route::post('tuition-packages/parse-csv-import', 'TuitionPackageController@parseCsvImport')->name('tuition-packages.parseCsvImport');
    Route::post('tuition-packages/process-csv-import', 'TuitionPackageController@processCsvImport')->name('tuition-packages.processCsvImport');
    Route::resource('tuition-packages', 'TuitionPackageController');

    // Tuition Gift
    Route::delete('tuition-gifts/destroy', 'TuitionGiftController@massDestroy')->name('tuition-gifts.massDestroy');
    Route::post('tuition-gifts/parse-csv-import', 'TuitionGiftController@parseCsvImport')->name('tuition-gifts.parseCsvImport');
    Route::post('tuition-gifts/process-csv-import', 'TuitionGiftController@processCsvImport')->name('tuition-gifts.processCsvImport');
    Route::resource('tuition-gifts', 'TuitionGiftController');

    // Student Tuition
    Route::delete('student-tuitions/destroy', 'StudentTuitionController@massDestroy')->name('student-tuitions.massDestroy');
    Route::post('student-tuitions/parse-csv-import', 'StudentTuitionController@parseCsvImport')->name('student-tuitions.parseCsvImport');
    Route::post('student-tuitions/process-csv-import', 'StudentTuitionController@processCsvImport')->name('student-tuitions.processCsvImport');
    Route::resource('student-tuitions', 'StudentTuitionController');

    // Lesson Level
    Route::delete('lesson-levels/destroy', 'LessonLevelController@massDestroy')->name('lesson-levels.massDestroy');
    Route::post('lesson-levels/parse-csv-import', 'LessonLevelController@parseCsvImport')->name('lesson-levels.parseCsvImport');
    Route::post('lesson-levels/process-csv-import', 'LessonLevelController@processCsvImport')->name('lesson-levels.processCsvImport');
    Route::resource('lesson-levels', 'LessonLevelController');

    // Lesson
    Route::delete('lessons/destroy', 'LessonController@massDestroy')->name('lessons.massDestroy');
    Route::post('lessons/parse-csv-import', 'LessonController@parseCsvImport')->name('lessons.parseCsvImport');
    Route::post('lessons/process-csv-import', 'LessonController@processCsvImport')->name('lessons.processCsvImport');
    Route::resource('lessons', 'LessonController');

    // Lesson Coach
    Route::delete('lesson-coaches/destroy', 'LessonCoachController@massDestroy')->name('lesson-coaches.massDestroy');
    Route::post('lesson-coaches/parse-csv-import', 'LessonCoachController@parseCsvImport')->name('lesson-coaches.parseCsvImport');
    Route::post('lesson-coaches/process-csv-import', 'LessonCoachController@processCsvImport')->name('lesson-coaches.processCsvImport');
    Route::resource('lesson-coaches', 'LessonCoachController');

    // Lesson Time
    Route::delete('lesson-times/destroy', 'LessonTimeController@massDestroy')->name('lesson-times.massDestroy');
    Route::post('lesson-times/parse-csv-import', 'LessonTimeController@parseCsvImport')->name('lesson-times.parseCsvImport');
    Route::post('lesson-times/process-csv-import', 'LessonTimeController@processCsvImport')->name('lesson-times.processCsvImport');
    Route::resource('lesson-times', 'LessonTimeController');

    // Lesson Time Coach
    Route::delete('lesson-time-coaches/destroy', 'LessonTimeCoachController@massDestroy')->name('lesson-time-coaches.massDestroy');
    Route::post('lesson-time-coaches/parse-csv-import', 'LessonTimeCoachController@parseCsvImport')->name('lesson-time-coaches.parseCsvImport');
    Route::post('lesson-time-coaches/process-csv-import', 'LessonTimeCoachController@processCsvImport')->name('lesson-time-coaches.processCsvImport');
    Route::resource('lesson-time-coaches', 'LessonTimeCoachController');

    // Lesson Time Change
    Route::delete('lesson-time-changes/destroy', 'LessonTimeChangeController@massDestroy')->name('lesson-time-changes.massDestroy');
    Route::post('lesson-time-changes/parse-csv-import', 'LessonTimeChangeController@parseCsvImport')->name('lesson-time-changes.parseCsvImport');
    Route::post('lesson-time-changes/process-csv-import', 'LessonTimeChangeController@processCsvImport')->name('lesson-time-changes.processCsvImport');
    Route::resource('lesson-time-changes', 'LessonTimeChangeController');

    // Student Lesson Progress
    Route::delete('student-lesson-progresses/destroy', 'StudentLessonProgressController@massDestroy')->name('student-lesson-progresses.massDestroy');
    Route::post('student-lesson-progresses/parse-csv-import', 'StudentLessonProgressController@parseCsvImport')->name('student-lesson-progresses.parseCsvImport');
    Route::post('student-lesson-progresses/process-csv-import', 'StudentLessonProgressController@processCsvImport')->name('student-lesson-progresses.processCsvImport');
    Route::resource('student-lesson-progresses', 'StudentLessonProgressController');

    // Student Detail
    Route::delete('student-details/destroy', 'StudentDetailController@massDestroy')->name('student-details.massDestroy');
    Route::post('student-details/parse-csv-import', 'StudentDetailController@parseCsvImport')->name('student-details.parseCsvImport');
    Route::post('student-details/process-csv-import', 'StudentDetailController@processCsvImport')->name('student-details.processCsvImport');
    Route::resource('student-details', 'StudentDetailController');

    // Student Meta
    Route::delete('student-meta/destroy', 'StudentMetaController@massDestroy')->name('student-meta.massDestroy');
    Route::post('student-meta/parse-csv-import', 'StudentMetaController@parseCsvImport')->name('student-meta.parseCsvImport');
    Route::post('student-meta/process-csv-import', 'StudentMetaController@processCsvImport')->name('student-meta.processCsvImport');
    Route::resource('student-meta', 'StudentMetaController');

    // Student Work
    Route::delete('student-works/destroy', 'StudentWorkController@massDestroy')->name('student-works.massDestroy');
    Route::post('student-works/parse-csv-import', 'StudentWorkController@parseCsvImport')->name('student-works.parseCsvImport');
    Route::post('student-works/process-csv-import', 'StudentWorkController@processCsvImport')->name('student-works.processCsvImport');
    Route::resource('student-works', 'StudentWorkController');

    // Submission
    Route::delete('submissions/destroy', 'SubmissionController@massDestroy')->name('submissions.massDestroy');
    Route::post('submissions/parse-csv-import', 'SubmissionController@parseCsvImport')->name('submissions.parseCsvImport');
    Route::post('submissions/process-csv-import', 'SubmissionController@processCsvImport')->name('submissions.processCsvImport');
    Route::resource('submissions', 'SubmissionController');

    // Work Resource
    Route::delete('work-resources/destroy', 'WorkResourceController@massDestroy')->name('work-resources.massDestroy');
    Route::post('work-resources/media', 'WorkResourceController@storeMedia')->name('work-resources.storeMedia');
    Route::post('work-resources/ckmedia', 'WorkResourceController@storeCKEditorImages')->name('work-resources.storeCKEditorImages');
    Route::post('work-resources/parse-csv-import', 'WorkResourceController@parseCsvImport')->name('work-resources.parseCsvImport');
    Route::post('work-resources/process-csv-import', 'WorkResourceController@processCsvImport')->name('work-resources.processCsvImport');
    Route::resource('work-resources', 'WorkResourceController');

    // Submit Resource
    Route::delete('submit-resources/destroy', 'SubmitResourceController@massDestroy')->name('submit-resources.massDestroy');
    Route::post('submit-resources/media', 'SubmitResourceController@storeMedia')->name('submit-resources.storeMedia');
    Route::post('submit-resources/ckmedia', 'SubmitResourceController@storeCKEditorImages')->name('submit-resources.storeCKEditorImages');
    Route::post('submit-resources/parse-csv-import', 'SubmitResourceController@parseCsvImport')->name('submit-resources.parseCsvImport');

app/Models/StudentTuition.php
<?php

namespace App\Models;

use \DateTimeInterface;
use App\Traits\Auditable;
use App\Traits\MultiTenantModelTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class StudentTuition extends Model
{
    use SoftDeletes;
    use MultiTenantModelTrait;
    use Auditable;
    use HasFactory;

    public $table = 'student_tuitions';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'minute_left',
        'tuition_package_id',
        'student_efk',
        'created_at',
        'updated_at',
        'deleted_at',
        'created_by_id',
    ];

    public function tuition_package()
    {
        return $this->belongsTo(TuitionPackage::class, 'tuition_package_id');
    }

    public function created_by()
    {
        return $this->belongsTo(User::class, 'created_by_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/StudentTuitionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\CsvImportTrait;
use App\Http\Requests\MassDestroyStudentTuitionRequest;
use App\Http\Requests\StoreStudentTuitionRequest;
use App\Http\Requests\UpdateStudentTuitionRequest;
use App\Models\StudentTuition;
use App\Models\TuitionPackage;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class StudentTuitionController extends Controller
{
    use CsvImportTrait;

    public function index(Request $request)
    {
        abort_if(Gate::denies('student_tuition_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = StudentTuition::with(['tuition_package', 'created_by'])->select(sprintf('%s.*', (new StudentTuition())->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate = 'student_tuition_show';
                $editGate = 'student_tuition_edit';
                $deleteGate = 'student_tuition_delete';
                $crudRoutePart = 'student-tuitions';

                return view('partials.datatablesActions', compact(
                'viewGate',
                'editGate',
                'deleteGate',
                'crudRoutePart',
                'row'
            ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : '';
            });
            $table->editColumn('minute_left', function ($row) {
                return $row->minute_left ? $row->minute_left : '';
            });
            $table->addColumn('tuition_package_name', function ($row) {
                return $row->tuition_package ? $row->tuition_package->name : '';
            });

            $table->editColumn('student_efk', function ($row) {
                return $row->student_efk ? $row->student_efk : '';
            });

            $table->rawColumns(['actions', 'placeholder', 'tuition_package']);

            return $table->make(true);
        }

        return view('admin.studentTuitions.index');
    }

    public function create()
    {
        abort_if(Gate::denies('student_tuition_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tuition_packages = TuitionPackage::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.studentTuitions.create', compact('tuition_packages'));
    }

    public function store(StoreStudentTuitionRequest $request)
    {
        $studentTuition = StudentTuition::create($request->all());

        return redirect()->route('admin.student-tuitions.index');
    }

    public function edit(StudentTuition $studentTuition)
    {
        abort_if(Gate::denies('student_tuition_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tuition_packages = TuitionPackage::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $studentTuition->load('tuition_package', 'created_by');

        return view('admin.studentTuitions.edit', compact('studentTuition', 'tuition_packages'));
    }

    public function update(UpdateStudentTuitionRequest $request, StudentTuition $studentTuition)
    {
        $studentTuition->update($request->all());

        return redirect()->route('admin.student-tuitions.index');
    }

    public function show(StudentTuition $studentTuition)
    {
        abort_if(Gate::denies('student_tuition_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $studentTuition->load('tuition_package', 'created_by');

        return view('admin.studentTuitions.show', compact('studentTuition'));
    }

    public function destroy(StudentTuition $studentTuition)
    {
        abort_if(Gate::denies('student_tuition_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $studentTuition->delete();

        return back();
    }

    public function massDestroy(MassDestroyStudentTuitionRequest $request)
    {
        StudentTuition::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/studentTuitions/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.studentTuition.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.student-tuitions.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="minute_left">{{ trans('cruds.studentTuition.fields.minute_left') }}</label>
                <input class="form-control {{ $errors->has('minute_left') ? 'is-invalid' : '' }}" type="number" name="minute_left" id="minute_left" value="{{ old('minute_left', '0') }}" step="0.01" required>
                @if($errors->has('minute_left'))
                    <div class="invalid-feedback">
                        {{ $errors->first('minute_left') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.studentTuition.fields.minute_left_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="tuition_package_id">{{ trans('cruds.studentTuition.fields.tuition_package') }}</label>
                <select class="form-control select2 {{ $errors->has('tuition_package') ? 'is-invalid' : '' }}" name="tuition_package_id" id="tuition_package_id">
                    @foreach($tuition_packages as $id => $entry)
                        <option value="{{ $id }}" {{ old('tuition_package_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('tuition_package'))
                    <div class="invalid-feedback">
                        {{ $errors->first('tuition_package') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.studentTuition.fields.tuition_package_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="student_efk">{{ trans('cruds.studentTuition.fields.student_efk') }}</label>
                <input class="form-control {{ $errors->has('student_efk') ? 'is-invalid' : '' }}" type="number" name="student_efk" id="student_efk" value="{{ old('student_efk', '') }}" step="1" required>
                @if($errors->has('student_efk'))
                    <div class="invalid-feedback">
                        {{ $errors->first('student_efk') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.studentTuition.fields.student_efk_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/studentTuitions/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.studentTuition.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.student-tuitions.update", [$studentTuition->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="minute_left">{{ trans('cruds.studentTuition.fields.minute_left') }}</label>
                <input class="form-control {{ $errors->has('minute_left') ? 'is-invalid' : '' }}" type="number" name="minute_left" id="minute_left" value="{{ old('minute_left', $studentTuition->minute_left) }}" step="0.01" required>
                @if($errors->has('minute_left'))
                    <div class="invalid-feedback">
                        {{ $errors->first('minute_left') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.studentTuition.fields.minute_left_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="tuition_package_id">{{ trans('cruds.studentTuition.fields.tuition_package') }}</label>
                <select class="form-control select2 {{ $errors->has('tuition_package') ? 'is-invalid' : '' }}" name="tuition_package_id" id="tuition_package_id">
                    @foreach($tuition_packages as $id => $entry)
                        <option value="{{ $id }}" {{ (old('tuition_package_id') ? old('tuition_package_id') : $studentTuition->tuition_package->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('tuition_package'))
                    <div class="invalid-feedback">
                        {{ $errors->first('tuition_package') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.studentTuition.fields.tuition_package_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="student_efk">{{ trans('cruds.studentTuition.fields.student_efk') }}</label>
                <input class="form-control {{ $errors->has('student_efk') ? 'is-invalid' : '' }}" type="number" name="student_efk" id="student_efk" value="{{ old('student_efk', $studentTuition->student_efk) }}" step="1" required>
                @if($errors->has('student_efk'))
                    <div class="invalid-feedback">
                        {{ $errors->first('student_efk') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.studentTuition.fields.student_efk_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/studentTuitions/index.blade.php
@extends('layouts.admin')
@section('content')
@can('student_tuition_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.student-tuitions.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.studentTuition.title_singular') }}
            </a>
            <button class="btn btn-warning" data-toggle="modal" data-target="#csvImportModal">
                {{ trans('global.app_csvImport') }}
            </button>
            @include('csvImport.modal', ['model' => 'StudentTuition', 'route' => 'admin.student-tuitions.parseCsvImport'])
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.studentTuition.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <table class=" table table-bordered table-striped table-hover ajaxTable datatable datatable-StudentTuition">
            <thead>
                <tr>
                    <th width="10">

                    </th>
                    <th>
                        {{ trans('cruds.studentTuition.fields.id') }}
                    </th>
                    <th>
                        {{ trans('cruds.studentTuition.fields.minute_left') }}
                    </th>
                    <th>
                        {{ trans('cruds.studentTuition.fields.tuition_package') }}
                    </th>
                    <th>
                        {{ trans('cruds.studentTuition.fields.student_efk') }}
                    </th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('student_tuition_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}';
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.student-tuitions.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).data(), function (entry) {
          return entry.id
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  let dtOverrideGlobals = {
    buttons: dtButtons,
    processing: true,
    serverSide: true,
    retrieve: true,
    aaSorting: [],
    ajax: "{{ route('admin.student-tuitions.index') }}",
    columns: [
      { data: 'placeholder', name: 'placeholder' },
{ data: 'id', name: 'id' },
{ data: 'minute_left', name: 'minute_left' },
{ data: 'tuition_package_name', name: 'tuition_package.name' },
{ data: 'student_efk', name: 'student_efk' },
{ data: 'actions', name: '{{ trans('global.actions') }}' }
    ],
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  };
  let table = $('.datatable-StudentTuition').DataTable(dtOverrideGlobals);
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
});

</script>
@endsection

resources/views/admin/studentTuitions/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.studentTuition.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.student-tuitions.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.studentTuition.fields.id') }}
                        </th>
                        <td>
                            {{ $studentTuition->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.studentTuition.fields.minute_left') }}
                        </th>
                        <td>
                            {{ $studentTuition->minute_left }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.studentTuition.fields.tuition_package') }}
                        </th>
                        <td>
                            {{ $studentTuition->tuition_package->name ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.studentTuition.fields.student_efk') }}
                        </th>
                        <td>
                            {{ $studentTuition->student_efk }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.student-tuitions.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection