routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Class Room
    Route::delete('class-rooms/destroy', 'ClassRoomController@massDestroy')->name('class-rooms.massDestroy');
    Route::post('class-rooms/parse-csv-import', 'ClassRoomController@parseCsvImport')->name('class-rooms.parseCsvImport');
    Route::post('class-rooms/process-csv-import', 'ClassRoomController@processCsvImport')->name('class-rooms.processCsvImport');
    Route::resource('class-rooms', 'ClassRoomController');

    // Lesson Category
    Route::delete('lesson-categories/destroy', 'LessonCategoryController@massDestroy')->name('lesson-categories.massDestroy');
    Route::post('lesson-categories/parse-csv-import', 'LessonCategoryController@parseCsvImport')->name('lesson-categories.parseCsvImport');
    Route::post('lesson-categories/process-csv-import', 'LessonCategoryController@processCsvImport')->name('lesson-categories.processCsvImport');
    Route::resource('lesson-categories', 'LessonCategoryController');

    // Tuition Package
    Route::delete('tuition-packages/destroy', 'TuitionPackageController@massDestroy')->name('tuition-packages.massDestroy');
    Route::post('tuition-packages/parse-csv-import', 'TuitionPackageController@parseCsvImport')->name('tuition-packages.parseCsvImport');
    Route::post('tuition-packages/process-csv-import', 'TuitionPackageController@processCsvImport')->name('tuition-packages.processCsvImport');
    Route::resource('tuition-packages', 'TuitionPackageController');

    // Tuition Gift
    Route::delete('tuition-gifts/destroy', 'TuitionGiftController@massDestroy')->name('tuition-gifts.massDestroy');
    Route::post('tuition-gifts/parse-csv-import', 'TuitionGiftController@parseCsvImport')->name('tuition-gifts.parseCsvImport');
    Route::post('tuition-gifts/process-csv-import', 'TuitionGiftController@processCsvImport')->name('tuition-gifts.processCsvImport');
    Route::resource('tuition-gifts', 'TuitionGiftController');

    // Student Tuition
    Route::delete('student-tuitions/destroy', 'StudentTuitionController@massDestroy')->name('student-tuitions.massDestroy');
    Route::post('student-tuitions/parse-csv-import', 'StudentTuitionController@parseCsvImport')->name('student-tuitions.parseCsvImport');
    Route::post('student-tuitions/process-csv-import', 'StudentTuitionController@processCsvImport')->name('student-tuitions.processCsvImport');
    Route::resource('student-tuitions', 'StudentTuitionController');

    // Lesson Level
    Route::delete('lesson-levels/destroy', 'LessonLevelController@massDestroy')->name('lesson-levels.massDestroy');
    Route::post('lesson-levels/parse-csv-import', 'LessonLevelController@parseCsvImport')->name('lesson-levels.parseCsvImport');
    Route::post('lesson-levels/process-csv-import', 'LessonLevelController@processCsvImport')->name('lesson-levels.processCsvImport');
    Route::resource('lesson-levels', 'LessonLevelController');

    // Lesson
    Route::delete('lessons/destroy', 'LessonController@massDestroy')->name('lessons.massDestroy');
    Route::post('lessons/parse-csv-import', 'LessonController@parseCsvImport')->name('lessons.parseCsvImport');
    Route::post('lessons/process-csv-import', 'LessonController@processCsvImport')->name('lessons.processCsvImport');
    Route::resource('lessons', 'LessonController');

    // Lesson Coach
    Route::delete('lesson-coaches/destroy', 'LessonCoachController@massDestroy')->name('lesson-coaches.massDestroy');
    Route::post('lesson-coaches/parse-csv-import', 'LessonCoachController@parseCsvImport')->name('lesson-coaches.parseCsvImport');
    Route::post('lesson-coaches/process-csv-import', 'LessonCoachController@processCsvImport')->name('lesson-coaches.processCsvImport');
    Route::resource('lesson-coaches', 'LessonCoachController');

    // Lesson Time
    Route::delete('lesson-times/destroy', 'LessonTimeController@massDestroy')->name('lesson-times.massDestroy');
    Route::post('lesson-times/parse-csv-import', 'LessonTimeController@parseCsvImport')->name('lesson-times.parseCsvImport');
    Route::post('lesson-times/process-csv-import', 'LessonTimeController@processCsvImport')->name('lesson-times.processCsvImport');
    Route::resource('lesson-times', 'LessonTimeController');

    // Lesson Time Coach
    Route::delete('lesson-time-coaches/destroy', 'LessonTimeCoachController@massDestroy')->name('lesson-time-coaches.massDestroy');
    Route::post('lesson-time-coaches/parse-csv-import', 'LessonTimeCoachController@parseCsvImport')->name('lesson-time-coaches.parseCsvImport');
    Route::post('lesson-time-coaches/process-csv-import', 'LessonTimeCoachController@processCsvImport')->name('lesson-time-coaches.processCsvImport');
    Route::resource('lesson-time-coaches', 'LessonTimeCoachController');

    // Lesson Time Change
    Route::delete('lesson-time-changes/destroy', 'LessonTimeChangeController@massDestroy')->name('lesson-time-changes.massDestroy');
    Route::post('lesson-time-changes/parse-csv-import', 'LessonTimeChangeController@parseCsvImport')->name('lesson-time-changes.parseCsvImport');
    Route::post('lesson-time-changes/process-csv-import', 'LessonTimeChangeController@processCsvImport')->name('lesson-time-changes.processCsvImport');
    Route::resource('lesson-time-changes', 'LessonTimeChangeController');

    // Student Lesson Progress
    Route::delete('student-lesson-progresses/destroy', 'StudentLessonProgressController@massDestroy')->name('student-lesson-progresses.massDestroy');
    Route::post('student-lesson-progresses/parse-csv-import', 'StudentLessonProgressController@parseCsvImport')->name('student-lesson-progresses.parseCsvImport');
    Route::post('student-lesson-progresses/process-csv-import', 'StudentLessonProgressController@processCsvImport')->name('student-lesson-progresses.processCsvImport');
    Route::resource('student-lesson-progresses', 'StudentLessonProgressController');

    // Student Detail
    Route::delete('student-details/destroy', 'StudentDetailController@massDestroy')->name('student-details.massDestroy');
    Route::post('student-details/parse-csv-import', 'StudentDetailController@parseCsvImport')->name('student-details.parseCsvImport');
    Route::post('student-details/process-csv-import', 'StudentDetailController@processCsvImport')->name('student-details.processCsvImport');
    Route::resource('student-details', 'StudentDetailController');

    // Student Meta
    Route::delete('student-meta/destroy', 'StudentMetaController@massDestroy')->name('student-meta.massDestroy');
    Route::post('student-meta/parse-csv-import', 'StudentMetaController@parseCsvImport')->name('student-meta.parseCsvImport');
    Route::post('student-meta/process-csv-import', 'StudentMetaController@processCsvImport')->name('student-meta.processCsvImport');
    Route::resource('student-meta', 'StudentMetaController');

    // Student Work
    Route::delete('student-works/destroy', 'StudentWorkController@massDestroy')->name('student-works.massDestroy');
    Route::post('student-works/parse-csv-import', 'StudentWorkController@parseCsvImport')->name('student-works.parseCsvImport');
    Route::post('student-works/process-csv-import', 'StudentWorkController@processCsvImport')->name('student-works.processCsvImport');
    Route::resource('student-works', 'StudentWorkController');

    // Submission
    Route::delete('submissions/destroy', 'SubmissionController@massDestroy')->name('submissions.massDestroy');
    Route::post('submissions/parse-csv-import', 'SubmissionController@parseCsvImport')->name('submissions.parseCsvImport');
    Route::post('submissions/process-csv-import', 'SubmissionController@processCsvImport')->name('submissions.processCsvImport');
    Route::resource('submissions', 'SubmissionController');

    // Work Resource
    Route::delete('work-resources/destroy', 'WorkResourceController@massDestroy')->name('work-resources.massDestroy');
    Route::post('work-resources/media', 'WorkResourceController@storeMedia')->name('work-resources.storeMedia');
    Route::post('work-resources/ckmedia', 'WorkResourceController@storeCKEditorImages')->name('work-resources.storeCKEditorImages');
    Route::post('work-resources/parse-csv-import', 'WorkResourceController@parseCsvImport')->name('work-resources.parseCsvImport');
    Route::post('work-resources/process-csv-import', 'WorkResourceController@processCsvImport')->name('work-resources.processCsvImport');
    Route::resource('work-resources', 'WorkResourceController');

    // Submit Resource
    Route::delete('submit-resources/destroy', 'SubmitResourceController@massDestroy')->name('submit-resources.massDestroy');
    Route::post('submit-resources/media', 'SubmitResourceController@storeMedia')->name('submit-resources.storeMedia');
    Route::post('submit-resources/ckmedia', 'SubmitResourceController@storeCKEditorImages')->name('submit-resources.storeCKEditorImages');
    Route::post('submit-resources/parse-csv-import', 'SubmitResourceController@parseCsvImport')->name('submit-resources.parseCsvImport');

app/Models/LessonCategory.php
<?php

namespace App\Models;

use \DateTimeInterface;
use App\Traits\Auditable;
use App\Traits\MultiTenantModelTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class LessonCategory extends Model
{
    use SoftDeletes;
    use MultiTenantModelTrait;
    use Auditable;
    use HasFactory;

    public const GROUP_SELECT = [
        'primary_class'   => 'Primary Class',
        'secondary_class' => 'Secondary Class',
        'public_class'    => 'Public Class',
    ];

    public $table = 'lesson_categories';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'desc',
        'group',
        'created_at',
        'updated_at',
        'deleted_at',
        'created_by_id',
    ];

    public function created_by()
    {
        return $this->belongsTo(User::class, 'created_by_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/LessonCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\CsvImportTrait;
use App\Http\Requests\MassDestroyLessonCategoryRequest;
use App\Http\Requests\StoreLessonCategoryRequest;
use App\Http\Requests\UpdateLessonCategoryRequest;
use App\Models\LessonCategory;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class LessonCategoryController extends Controller
{
    use CsvImportTrait;

    public function index(Request $request)
    {
        abort_if(Gate::denies('lesson_category_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = LessonCategory::with(['created_by'])->select(sprintf('%s.*', (new LessonCategory())->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate = 'lesson_category_show';
                $editGate = 'lesson_category_edit';
                $deleteGate = 'lesson_category_delete';
                $crudRoutePart = 'lesson-categories';

                return view('partials.datatablesActions', compact(
                'viewGate',
                'editGate',
                'deleteGate',
                'crudRoutePart',
                'row'
            ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : '';
            });
            $table->editColumn('name', function ($row) {
                return $row->name ? $row->name : '';
            });
            $table->editColumn('desc', function ($row) {
                return $row->desc ? $row->desc : '';
            });
            $table->editColumn('group', function ($row) {
                return $row->group ? LessonCategory::GROUP_SELECT[$row->group] : '';
            });

            $table->rawColumns(['actions', 'placeholder']);

            return $table->make(true);
        }

        return view('admin.lessonCategories.index');
    }

    public function create()
    {
        abort_if(Gate::denies('lesson_category_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.lessonCategories.create');
    }

    public function store(StoreLessonCategoryRequest $request)
    {
        $lessonCategory = LessonCategory::create($request->all());

        return redirect()->route('admin.lesson-categories.index');
    }

    public function edit(LessonCategory $lessonCategory)
    {
        abort_if(Gate::denies('lesson_category_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $lessonCategory->load('created_by');

        return view('admin.lessonCategories.edit', compact('lessonCategory'));
    }

    public function update(UpdateLessonCategoryRequest $request, LessonCategory $lessonCategory)
    {
        $lessonCategory->update($request->all());

        return redirect()->route('admin.lesson-categories.index');
    }

    public function show(LessonCategory $lessonCategory)
    {
        abort_if(Gate::denies('lesson_category_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $lessonCategory->load('created_by');

        return view('admin.lessonCategories.show', compact('lessonCategory'));
    }

    public function destroy(LessonCategory $lessonCategory)
    {
        abort_if(Gate::denies('lesson_category_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $lessonCategory->delete();

        return back();
    }

    public function massDestroy(MassDestroyLessonCategoryRequest $request)
    {
        LessonCategory::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/lessonCategories/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.lessonCategory.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.lesson-categories.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.lessonCategory.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.lessonCategory.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="desc">{{ trans('cruds.lessonCategory.fields.desc') }}</label>
                <input class="form-control {{ $errors->has('desc') ? 'is-invalid' : '' }}" type="text" name="desc" id="desc" value="{{ old('desc', '') }}">
                @if($errors->has('desc'))
                    <div class="invalid-feedback">
                        {{ $errors->first('desc') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.lessonCategory.fields.desc_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required">{{ trans('cruds.lessonCategory.fields.group') }}</label>
                <select class="form-control {{ $errors->has('group') ? 'is-invalid' : '' }}" name="group" id="group" required>
                    <option value disabled {{ old('group', null) === null ? 'selected' : '' }}>{{ trans('global.pleaseSelect') }}</option>
                    @foreach(App\Models\LessonCategory::GROUP_SELECT as $key => $label)
                        <option value="{{ $key }}" {{ old('group', '') === (string) $key ? 'selected' : '' }}>{{ $label }}</option>
                    @endforeach
                </select>
                @if($errors->has('group'))
                    <div class="invalid-feedback">
                        {{ $errors->first('group') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.lessonCategory.fields.group_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/lessonCategories/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.lessonCategory.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.lesson-categories.update", [$lessonCategory->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.lessonCategory.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $lessonCategory->name) }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.lessonCategory.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="desc">{{ trans('cruds.lessonCategory.fields.desc') }}</label>
                <input class="form-control {{ $errors->has('desc') ? 'is-invalid' : '' }}" type="text" name="desc" id="desc" value="{{ old('desc', $lessonCategory->desc) }}">
                @if($errors->has('desc'))
                    <div class="invalid-feedback">
                        {{ $errors->first('desc') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.lessonCategory.fields.desc_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required">{{ trans('cruds.lessonCategory.fields.group') }}</label>
                <select class="form-control {{ $errors->has('group') ? 'is-invalid' : '' }}" name="group" id="group" required>
                    <option value disabled {{ old('group', null) === null ? 'selected' : '' }}>{{ trans('global.pleaseSelect') }}</option>
                    @foreach(App\Models\LessonCategory::GROUP_SELECT as $key => $label)
                        <option value="{{ $key }}" {{ old('group', $lessonCategory->group) === (string) $key ? 'selected' : '' }}>{{ $label }}</option>
                    @endforeach
                </select>
                @if($errors->has('group'))
                    <div class="invalid-feedback">
                        {{ $errors->first('group') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.lessonCategory.fields.group_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/lessonCategories/index.blade.php
@extends('layouts.admin')
@section('content')
@can('lesson_category_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.lesson-categories.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.lessonCategory.title_singular') }}
            </a>
            <button class="btn btn-warning" data-toggle="modal" data-target="#csvImportModal">
                {{ trans('global.app_csvImport') }}
            </button>
            @include('csvImport.modal', ['model' => 'LessonCategory', 'route' => 'admin.lesson-categories.parseCsvImport'])
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.lessonCategory.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <table class=" table table-bordered table-striped table-hover ajaxTable datatable datatable-LessonCategory">
            <thead>
                <tr>
                    <th width="10">

                    </th>
                    <th>
                        {{ trans('cruds.lessonCategory.fields.id') }}
                    </th>
                    <th>
                        {{ trans('cruds.lessonCategory.fields.name') }}
                    </th>
                    <th>
                        {{ trans('cruds.lessonCategory.fields.desc') }}
                    </th>
                    <th>
                        {{ trans('cruds.lessonCategory.fields.group') }}
                    </th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('lesson_category_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}';
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.lesson-categories.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).data(), function (entry) {
          return entry.id
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  let dtOverrideGlobals = {
    buttons: dtButtons,
    processing: true,
    serverSide: true,
    retrieve: true,
    aaSorting: [],
    ajax: "{{ route('admin.lesson-categories.index') }}",
    columns: [
      { data: 'placeholder', name: 'placeholder' },
{ data: 'id', name: 'id' },
{ data: 'name', name: 'name' },
{ data: 'desc', name: 'desc' },
{ data: 'group', name: 'group' },
{ data: 'actions', name: '{{ trans('global.actions') }}' }
    ],
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  };
  let table = $('.datatable-LessonCategory').DataTable(dtOverrideGlobals);
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
});

</script>
@endsection

resources/views/admin/lessonCategories/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.lessonCategory.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.lesson-categories.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.lessonCategory.fields.id') }}
                        </th>
                        <td>
                            {{ $lessonCategory->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.lessonCategory.fields.name') }}
                        </th>
                        <td>
                            {{ $lessonCategory->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.lessonCategory.fields.desc') }}
                        </th>
                        <td>
                            {{ $lessonCategory->desc }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.lessonCategory.fields.group') }}
                        </th>
                        <td>
                            {{ App\Models\LessonCategory::GROUP_SELECT[$lessonCategory->group] ?? '' }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.lesson-categories.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection