routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Class Room
    Route::delete('class-rooms/destroy', 'ClassRoomController@massDestroy')->name('class-rooms.massDestroy');
    Route::post('class-rooms/parse-csv-import', 'ClassRoomController@parseCsvImport')->name('class-rooms.parseCsvImport');
    Route::post('class-rooms/process-csv-import', 'ClassRoomController@processCsvImport')->name('class-rooms.processCsvImport');
    Route::resource('class-rooms', 'ClassRoomController');

    // Lesson Category
    Route::delete('lesson-categories/destroy', 'LessonCategoryController@massDestroy')->name('lesson-categories.massDestroy');
    Route::post('lesson-categories/parse-csv-import', 'LessonCategoryController@parseCsvImport')->name('lesson-categories.parseCsvImport');
    Route::post('lesson-categories/process-csv-import', 'LessonCategoryController@processCsvImport')->name('lesson-categories.processCsvImport');
    Route::resource('lesson-categories', 'LessonCategoryController');

    // Tuition Package
    Route::delete('tuition-packages/destroy', 'TuitionPackageController@massDestroy')->name('tuition-packages.massDestroy');
    Route::post('tuition-packages/parse-csv-import', 'TuitionPackageController@parseCsvImport')->name('tuition-packages.parseCsvImport');
    Route::post('tuition-packages/process-csv-import', 'TuitionPackageController@processCsvImport')->name('tuition-packages.processCsvImport');
    Route::resource('tuition-packages', 'TuitionPackageController');

    // Tuition Gift
    Route::delete('tuition-gifts/destroy', 'TuitionGiftController@massDestroy')->name('tuition-gifts.massDestroy');
    Route::post('tuition-gifts/parse-csv-import', 'TuitionGiftController@parseCsvImport')->name('tuition-gifts.parseCsvImport');
    Route::post('tuition-gifts/process-csv-import', 'TuitionGiftController@processCsvImport')->name('tuition-gifts.processCsvImport');
    Route::resource('tuition-gifts', 'TuitionGiftController');

    // Student Tuition
    Route::delete('student-tuitions/destroy', 'StudentTuitionController@massDestroy')->name('student-tuitions.massDestroy');
    Route::post('student-tuitions/parse-csv-import', 'StudentTuitionController@parseCsvImport')->name('student-tuitions.parseCsvImport');
    Route::post('student-tuitions/process-csv-import', 'StudentTuitionController@processCsvImport')->name('student-tuitions.processCsvImport');
    Route::resource('student-tuitions', 'StudentTuitionController');

    // Lesson Level
    Route::delete('lesson-levels/destroy', 'LessonLevelController@massDestroy')->name('lesson-levels.massDestroy');
    Route::post('lesson-levels/parse-csv-import', 'LessonLevelController@parseCsvImport')->name('lesson-levels.parseCsvImport');
    Route::post('lesson-levels/process-csv-import', 'LessonLevelController@processCsvImport')->name('lesson-levels.processCsvImport');
    Route::resource('lesson-levels', 'LessonLevelController');

    // Lesson
    Route::delete('lessons/destroy', 'LessonController@massDestroy')->name('lessons.massDestroy');
    Route::post('lessons/parse-csv-import', 'LessonController@parseCsvImport')->name('lessons.parseCsvImport');
    Route::post('lessons/process-csv-import', 'LessonController@processCsvImport')->name('lessons.processCsvImport');
    Route::resource('lessons', 'LessonController');

    // Lesson Coach
    Route::delete('lesson-coaches/destroy', 'LessonCoachController@massDestroy')->name('lesson-coaches.massDestroy');
    Route::post('lesson-coaches/parse-csv-import', 'LessonCoachController@parseCsvImport')->name('lesson-coaches.parseCsvImport');
    Route::post('lesson-coaches/process-csv-import', 'LessonCoachController@processCsvImport')->name('lesson-coaches.processCsvImport');
    Route::resource('lesson-coaches', 'LessonCoachController');

    // Lesson Time
    Route::delete('lesson-times/destroy', 'LessonTimeController@massDestroy')->name('lesson-times.massDestroy');
    Route::post('lesson-times/parse-csv-import', 'LessonTimeController@parseCsvImport')->name('lesson-times.parseCsvImport');
    Route::post('lesson-times/process-csv-import', 'LessonTimeController@processCsvImport')->name('lesson-times.processCsvImport');
    Route::resource('lesson-times', 'LessonTimeController');

    // Lesson Time Coach
    Route::delete('lesson-time-coaches/destroy', 'LessonTimeCoachController@massDestroy')->name('lesson-time-coaches.massDestroy');
    Route::post('lesson-time-coaches/parse-csv-import', 'LessonTimeCoachController@parseCsvImport')->name('lesson-time-coaches.parseCsvImport');
    Route::post('lesson-time-coaches/process-csv-import', 'LessonTimeCoachController@processCsvImport')->name('lesson-time-coaches.processCsvImport');
    Route::resource('lesson-time-coaches', 'LessonTimeCoachController');

    // Lesson Time Change
    Route::delete('lesson-time-changes/destroy', 'LessonTimeChangeController@massDestroy')->name('lesson-time-changes.massDestroy');
    Route::post('lesson-time-changes/parse-csv-import', 'LessonTimeChangeController@parseCsvImport')->name('lesson-time-changes.parseCsvImport');
    Route::post('lesson-time-changes/process-csv-import', 'LessonTimeChangeController@processCsvImport')->name('lesson-time-changes.processCsvImport');
    Route::resource('lesson-time-changes', 'LessonTimeChangeController');

    // Student Lesson Progress
    Route::delete('student-lesson-progresses/destroy', 'StudentLessonProgressController@massDestroy')->name('student-lesson-progresses.massDestroy');
    Route::post('student-lesson-progresses/parse-csv-import', 'StudentLessonProgressController@parseCsvImport')->name('student-lesson-progresses.parseCsvImport');
    Route::post('student-lesson-progresses/process-csv-import', 'StudentLessonProgressController@processCsvImport')->name('student-lesson-progresses.processCsvImport');
    Route::resource('student-lesson-progresses', 'StudentLessonProgressController');

    // Student Detail
    Route::delete('student-details/destroy', 'StudentDetailController@massDestroy')->name('student-details.massDestroy');
    Route::post('student-details/parse-csv-import', 'StudentDetailController@parseCsvImport')->name('student-details.parseCsvImport');
    Route::post('student-details/process-csv-import', 'StudentDetailController@processCsvImport')->name('student-details.processCsvImport');
    Route::resource('student-details', 'StudentDetailController');

    // Student Meta
    Route::delete('student-meta/destroy', 'StudentMetaController@massDestroy')->name('student-meta.massDestroy');
    Route::post('student-meta/parse-csv-import', 'StudentMetaController@parseCsvImport')->name('student-meta.parseCsvImport');
    Route::post('student-meta/process-csv-import', 'StudentMetaController@processCsvImport')->name('student-meta.processCsvImport');
    Route::resource('student-meta', 'StudentMetaController');

    // Student Work
    Route::delete('student-works/destroy', 'StudentWorkController@massDestroy')->name('student-works.massDestroy');
    Route::post('student-works/parse-csv-import', 'StudentWorkController@parseCsvImport')->name('student-works.parseCsvImport');
    Route::post('student-works/process-csv-import', 'StudentWorkController@processCsvImport')->name('student-works.processCsvImport');
    Route::resource('student-works', 'StudentWorkController');

    // Submission
    Route::delete('submissions/destroy', 'SubmissionController@massDestroy')->name('submissions.massDestroy');
    Route::post('submissions/parse-csv-import', 'SubmissionController@parseCsvImport')->name('submissions.parseCsvImport');
    Route::post('submissions/process-csv-import', 'SubmissionController@processCsvImport')->name('submissions.processCsvImport');
    Route::resource('submissions', 'SubmissionController');

    // Work Resource
    Route::delete('work-resources/destroy', 'WorkResourceController@massDestroy')->name('work-resources.massDestroy');
    Route::post('work-resources/media', 'WorkResourceController@storeMedia')->name('work-resources.storeMedia');
    Route::post('work-resources/ckmedia', 'WorkResourceController@storeCKEditorImages')->name('work-resources.storeCKEditorImages');
    Route::post('work-resources/parse-csv-import', 'WorkResourceController@parseCsvImport')->name('work-resources.parseCsvImport');
    Route::post('work-resources/process-csv-import', 'WorkResourceController@processCsvImport')->name('work-resources.processCsvImport');
    Route::resource('work-resources', 'WorkResourceController');

    // Submit Resource
    Route::delete('submit-resources/destroy', 'SubmitResourceController@massDestroy')->name('submit-resources.massDestroy');
    Route::post('submit-resources/media', 'SubmitResourceController@storeMedia')->name('submit-resources.storeMedia');
    Route::post('submit-resources/ckmedia', 'SubmitResourceController@storeCKEditorImages')->name('submit-resources.storeCKEditorImages');
    Route::post('submit-resources/parse-csv-import', 'SubmitResourceController@parseCsvImport')->name('submit-resources.parseCsvImport');

app/Models/TuitionPackage.php
<?php

namespace App\Models;

use \DateTimeInterface;
use App\Traits\Auditable;
use App\Traits\MultiTenantModelTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class TuitionPackage extends Model
{
    use SoftDeletes;
    use MultiTenantModelTrait;
    use Auditable;
    use HasFactory;

    public $table = 'tuition_packages';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'price',
        'total_minute',
        'lesson_category_id',
        'created_at',
        'updated_at',
        'deleted_at',
        'created_by_id',
    ];

    public function lesson_category()
    {
        return $this->belongsTo(LessonCategory::class, 'lesson_category_id');
    }

    public function created_by()
    {
        return $this->belongsTo(User::class, 'created_by_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/TuitionPackageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\CsvImportTrait;
use App\Http\Requests\MassDestroyTuitionPackageRequest;
use App\Http\Requests\StoreTuitionPackageRequest;
use App\Http\Requests\UpdateTuitionPackageRequest;
use App\Models\LessonCategory;
use App\Models\TuitionPackage;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class TuitionPackageController extends Controller
{
    use CsvImportTrait;

    public function index(Request $request)
    {
        abort_if(Gate::denies('tuition_package_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = TuitionPackage::with(['lesson_category', 'created_by'])->select(sprintf('%s.*', (new TuitionPackage())->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate = 'tuition_package_show';
                $editGate = 'tuition_package_edit';
                $deleteGate = 'tuition_package_delete';
                $crudRoutePart = 'tuition-packages';

                return view('partials.datatablesActions', compact(
                'viewGate',
                'editGate',
                'deleteGate',
                'crudRoutePart',
                'row'
            ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : '';
            });
            $table->editColumn('name', function ($row) {
                return $row->name ? $row->name : '';
            });
            $table->editColumn('price', function ($row) {
                return $row->price ? $row->price : '';
            });
            $table->editColumn('total_minute', function ($row) {
                return $row->total_minute ? $row->total_minute : '';
            });
            $table->addColumn('lesson_category_name', function ($row) {
                return $row->lesson_category ? $row->lesson_category->name : '';
            });

            $table->rawColumns(['actions', 'placeholder', 'lesson_category']);

            return $table->make(true);
        }

        return view('admin.tuitionPackages.index');
    }

    public function create()
    {
        abort_if(Gate::denies('tuition_package_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $lesson_categories = LessonCategory::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.tuitionPackages.create', compact('lesson_categories'));
    }

    public function store(StoreTuitionPackageRequest $request)
    {
        $tuitionPackage = TuitionPackage::create($request->all());

        return redirect()->route('admin.tuition-packages.index');
    }

    public function edit(TuitionPackage $tuitionPackage)
    {
        abort_if(Gate::denies('tuition_package_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $lesson_categories = LessonCategory::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $tuitionPackage->load('lesson_category', 'created_by');

        return view('admin.tuitionPackages.edit', compact('lesson_categories', 'tuitionPackage'));
    }

    public function update(UpdateTuitionPackageRequest $request, TuitionPackage $tuitionPackage)
    {
        $tuitionPackage->update($request->all());

        return redirect()->route('admin.tuition-packages.index');
    }

    public function show(TuitionPackage $tuitionPackage)
    {
        abort_if(Gate::denies('tuition_package_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tuitionPackage->load('lesson_category', 'created_by');

        return view('admin.tuitionPackages.show', compact('tuitionPackage'));
    }

    public function destroy(TuitionPackage $tuitionPackage)
    {
        abort_if(Gate::denies('tuition_package_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tuitionPackage->delete();

        return back();
    }

    public function massDestroy(MassDestroyTuitionPackageRequest $request)
    {
        TuitionPackage::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/tuitionPackages/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.tuitionPackage.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.tuition-packages.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.tuitionPackage.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.tuitionPackage.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="price">{{ trans('cruds.tuitionPackage.fields.price') }}</label>
                <input class="form-control {{ $errors->has('price') ? 'is-invalid' : '' }}" type="number" name="price" id="price" value="{{ old('price', '0') }}" step="0.01" required>
                @if($errors->has('price'))
                    <div class="invalid-feedback">
                        {{ $errors->first('price') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.tuitionPackage.fields.price_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="total_minute">{{ trans('cruds.tuitionPackage.fields.total_minute') }}</label>
                <input class="form-control {{ $errors->has('total_minute') ? 'is-invalid' : '' }}" type="number" name="total_minute" id="total_minute" value="{{ old('total_minute', '0') }}" step="0.01" required>
                @if($errors->has('total_minute'))
                    <div class="invalid-feedback">
                        {{ $errors->first('total_minute') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.tuitionPackage.fields.total_minute_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="lesson_category_id">{{ trans('cruds.tuitionPackage.fields.lesson_category') }}</label>
                <select class="form-control select2 {{ $errors->has('lesson_category') ? 'is-invalid' : '' }}" name="lesson_category_id" id="lesson_category_id">
                    @foreach($lesson_categories as $id => $entry)
                        <option value="{{ $id }}" {{ old('lesson_category_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('lesson_category'))
                    <div class="invalid-feedback">
                        {{ $errors->first('lesson_category') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.tuitionPackage.fields.lesson_category_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/tuitionPackages/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.tuitionPackage.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.tuition-packages.update", [$tuitionPackage->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.tuitionPackage.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $tuitionPackage->name) }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.tuitionPackage.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="price">{{ trans('cruds.tuitionPackage.fields.price') }}</label>
                <input class="form-control {{ $errors->has('price') ? 'is-invalid' : '' }}" type="number" name="price" id="price" value="{{ old('price', $tuitionPackage->price) }}" step="0.01" required>
                @if($errors->has('price'))
                    <div class="invalid-feedback">
                        {{ $errors->first('price') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.tuitionPackage.fields.price_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="total_minute">{{ trans('cruds.tuitionPackage.fields.total_minute') }}</label>
                <input class="form-control {{ $errors->has('total_minute') ? 'is-invalid' : '' }}" type="number" name="total_minute" id="total_minute" value="{{ old('total_minute', $tuitionPackage->total_minute) }}" step="0.01" required>
                @if($errors->has('total_minute'))
                    <div class="invalid-feedback">
                        {{ $errors->first('total_minute') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.tuitionPackage.fields.total_minute_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="lesson_category_id">{{ trans('cruds.tuitionPackage.fields.lesson_category') }}</label>
                <select class="form-control select2 {{ $errors->has('lesson_category') ? 'is-invalid' : '' }}" name="lesson_category_id" id="lesson_category_id">
                    @foreach($lesson_categories as $id => $entry)
                        <option value="{{ $id }}" {{ (old('lesson_category_id') ? old('lesson_category_id') : $tuitionPackage->lesson_category->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('lesson_category'))
                    <div class="invalid-feedback">
                        {{ $errors->first('lesson_category') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.tuitionPackage.fields.lesson_category_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/tuitionPackages/index.blade.php
@extends('layouts.admin')
@section('content')
@can('tuition_package_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.tuition-packages.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.tuitionPackage.title_singular') }}
            </a>
            <button class="btn btn-warning" data-toggle="modal" data-target="#csvImportModal">
                {{ trans('global.app_csvImport') }}
            </button>
            @include('csvImport.modal', ['model' => 'TuitionPackage', 'route' => 'admin.tuition-packages.parseCsvImport'])
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.tuitionPackage.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <table class=" table table-bordered table-striped table-hover ajaxTable datatable datatable-TuitionPackage">
            <thead>
                <tr>
                    <th width="10">

                    </th>
                    <th>
                        {{ trans('cruds.tuitionPackage.fields.id') }}
                    </th>
                    <th>
                        {{ trans('cruds.tuitionPackage.fields.name') }}
                    </th>
                    <th>
                        {{ trans('cruds.tuitionPackage.fields.price') }}
                    </th>
                    <th>
                        {{ trans('cruds.tuitionPackage.fields.total_minute') }}
                    </th>
                    <th>
                        {{ trans('cruds.tuitionPackage.fields.lesson_category') }}
                    </th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('tuition_package_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}';
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.tuition-packages.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).data(), function (entry) {
          return entry.id
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  let dtOverrideGlobals = {
    buttons: dtButtons,
    processing: true,
    serverSide: true,
    retrieve: true,
    aaSorting: [],
    ajax: "{{ route('admin.tuition-packages.index') }}",
    columns: [
      { data: 'placeholder', name: 'placeholder' },
{ data: 'id', name: 'id' },
{ data: 'name', name: 'name' },
{ data: 'price', name: 'price' },
{ data: 'total_minute', name: 'total_minute' },
{ data: 'lesson_category_name', name: 'lesson_category.name' },
{ data: 'actions', name: '{{ trans('global.actions') }}' }
    ],
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  };
  let table = $('.datatable-TuitionPackage').DataTable(dtOverrideGlobals);
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
});

</script>
@endsection

resources/views/admin/tuitionPackages/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.tuitionPackage.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.tuition-packages.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.tuitionPackage.fields.id') }}
                        </th>
                        <td>
                            {{ $tuitionPackage->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tuitionPackage.fields.name') }}
                        </th>
                        <td>
                            {{ $tuitionPackage->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tuitionPackage.fields.price') }}
                        </th>
                        <td>
                            {{ $tuitionPackage->price }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tuitionPackage.fields.total_minute') }}
                        </th>
                        <td>
                            {{ $tuitionPackage->total_minute }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tuitionPackage.fields.lesson_category') }}
                        </th>
                        <td>
                            {{ $tuitionPackage->lesson_category->name ?? '' }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.tuition-packages.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection